# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sanguinus/hojonathanho-bulletsim-56b8d9e

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sanguinus/hojonathanho-bulletsim-56b8d9e

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sanguinus/hojonathanho-bulletsim-56b8d9e/CMakeFiles /home/sanguinus/hojonathanho-bulletsim-56b8d9e/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sanguinus/hojonathanho-bulletsim-56b8d9e/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named haptics

# Build rule for target.
haptics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 haptics
.PHONY : haptics

# fast build rule for target.
haptics/fast:
	$(MAKE) -f lib/haptics/CMakeFiles/haptics.dir/build.make lib/haptics/CMakeFiles/haptics.dir/build
.PHONY : haptics/fast

#=============================================================================
# Target rules for targets named AppHelloWorld

# Build rule for target.
AppHelloWorld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppHelloWorld
.PHONY : AppHelloWorld

# fast build rule for target.
AppHelloWorld/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/HelloWorld/CMakeFiles/AppHelloWorld.dir/build.make lib/bullet-2.79/Demos/HelloWorld/CMakeFiles/AppHelloWorld.dir/build
.PHONY : AppHelloWorld/fast

#=============================================================================
# Target rules for targets named OpenGLSupport

# Build rule for target.
OpenGLSupport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenGLSupport
.PHONY : OpenGLSupport

# fast build rule for target.
OpenGLSupport/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/OpenGL/CMakeFiles/OpenGLSupport.dir/build.make lib/bullet-2.79/Demos/OpenGL/CMakeFiles/OpenGLSupport.dir/build
.PHONY : OpenGLSupport/fast

#=============================================================================
# Target rules for targets named AppAllBulletDemos

# Build rule for target.
AppAllBulletDemos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppAllBulletDemos
.PHONY : AppAllBulletDemos

# fast build rule for target.
AppAllBulletDemos/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/AllBulletDemos/CMakeFiles/AppAllBulletDemos.dir/build.make lib/bullet-2.79/Demos/AllBulletDemos/CMakeFiles/AppAllBulletDemos.dir/build
.PHONY : AppAllBulletDemos/fast

#=============================================================================
# Target rules for targets named AppConvexDecompositionDemo

# Build rule for target.
AppConvexDecompositionDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppConvexDecompositionDemo
.PHONY : AppConvexDecompositionDemo

# fast build rule for target.
AppConvexDecompositionDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ConvexDecompositionDemo/CMakeFiles/AppConvexDecompositionDemo.dir/build.make lib/bullet-2.79/Demos/ConvexDecompositionDemo/CMakeFiles/AppConvexDecompositionDemo.dir/build
.PHONY : AppConvexDecompositionDemo/fast

#=============================================================================
# Target rules for targets named AppCcdPhysicsDemo

# Build rule for target.
AppCcdPhysicsDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppCcdPhysicsDemo
.PHONY : AppCcdPhysicsDemo

# fast build rule for target.
AppCcdPhysicsDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/CcdPhysicsDemo/CMakeFiles/AppCcdPhysicsDemo.dir/build.make lib/bullet-2.79/Demos/CcdPhysicsDemo/CMakeFiles/AppCcdPhysicsDemo.dir/build
.PHONY : AppCcdPhysicsDemo/fast

#=============================================================================
# Target rules for targets named AppConstraintDemo

# Build rule for target.
AppConstraintDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppConstraintDemo
.PHONY : AppConstraintDemo

# fast build rule for target.
AppConstraintDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ConstraintDemo/CMakeFiles/AppConstraintDemo.dir/build.make lib/bullet-2.79/Demos/ConstraintDemo/CMakeFiles/AppConstraintDemo.dir/build
.PHONY : AppConstraintDemo/fast

#=============================================================================
# Target rules for targets named AppSliderConstraintDemo

# Build rule for target.
AppSliderConstraintDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppSliderConstraintDemo
.PHONY : AppSliderConstraintDemo

# fast build rule for target.
AppSliderConstraintDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/SliderConstraintDemo/CMakeFiles/AppSliderConstraintDemo.dir/build.make lib/bullet-2.79/Demos/SliderConstraintDemo/CMakeFiles/AppSliderConstraintDemo.dir/build
.PHONY : AppSliderConstraintDemo/fast

#=============================================================================
# Target rules for targets named AppGenericJointDemo

# Build rule for target.
AppGenericJointDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppGenericJointDemo
.PHONY : AppGenericJointDemo

# fast build rule for target.
AppGenericJointDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/GenericJointDemo/CMakeFiles/AppGenericJointDemo.dir/build.make lib/bullet-2.79/Demos/GenericJointDemo/CMakeFiles/AppGenericJointDemo.dir/build
.PHONY : AppGenericJointDemo/fast

#=============================================================================
# Target rules for targets named AppRaytracer

# Build rule for target.
AppRaytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppRaytracer
.PHONY : AppRaytracer

# fast build rule for target.
AppRaytracer/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/Raytracer/CMakeFiles/AppRaytracer.dir/build.make lib/bullet-2.79/Demos/Raytracer/CMakeFiles/AppRaytracer.dir/build
.PHONY : AppRaytracer/fast

#=============================================================================
# Target rules for targets named AppRagdollDemo

# Build rule for target.
AppRagdollDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppRagdollDemo
.PHONY : AppRagdollDemo

# fast build rule for target.
AppRagdollDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/RagdollDemo/CMakeFiles/AppRagdollDemo.dir/build.make lib/bullet-2.79/Demos/RagdollDemo/CMakeFiles/AppRagdollDemo.dir/build
.PHONY : AppRagdollDemo/fast

#=============================================================================
# Target rules for targets named AppForkLiftDemo

# Build rule for target.
AppForkLiftDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppForkLiftDemo
.PHONY : AppForkLiftDemo

# fast build rule for target.
AppForkLiftDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ForkLiftDemo/CMakeFiles/AppForkLiftDemo.dir/build.make lib/bullet-2.79/Demos/ForkLiftDemo/CMakeFiles/AppForkLiftDemo.dir/build
.PHONY : AppForkLiftDemo/fast

#=============================================================================
# Target rules for targets named AppBasicDemo

# Build rule for target.
AppBasicDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppBasicDemo
.PHONY : AppBasicDemo

# fast build rule for target.
AppBasicDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/BasicDemo/CMakeFiles/AppBasicDemo.dir/build.make lib/bullet-2.79/Demos/BasicDemo/CMakeFiles/AppBasicDemo.dir/build
.PHONY : AppBasicDemo/fast

#=============================================================================
# Target rules for targets named AppFractureDemo

# Build rule for target.
AppFractureDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppFractureDemo
.PHONY : AppFractureDemo

# fast build rule for target.
AppFractureDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/FractureDemo/CMakeFiles/AppFractureDemo.dir/build.make lib/bullet-2.79/Demos/FractureDemo/CMakeFiles/AppFractureDemo.dir/build
.PHONY : AppFractureDemo/fast

#=============================================================================
# Target rules for targets named AppBox2dDemo

# Build rule for target.
AppBox2dDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppBox2dDemo
.PHONY : AppBox2dDemo

# fast build rule for target.
AppBox2dDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/Box2dDemo/CMakeFiles/AppBox2dDemo.dir/build.make lib/bullet-2.79/Demos/Box2dDemo/CMakeFiles/AppBox2dDemo.dir/build
.PHONY : AppBox2dDemo/fast

#=============================================================================
# Target rules for targets named AppBspPhysicsDemo

# Build rule for target.
AppBspPhysicsDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppBspPhysicsDemo
.PHONY : AppBspPhysicsDemo

# fast build rule for target.
AppBspPhysicsDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/BspDemo/CMakeFiles/AppBspPhysicsDemo.dir/build.make lib/bullet-2.79/Demos/BspDemo/CMakeFiles/AppBspPhysicsDemo.dir/build
.PHONY : AppBspPhysicsDemo/fast

#=============================================================================
# Target rules for targets named AppMovingConcaveDemo

# Build rule for target.
AppMovingConcaveDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppMovingConcaveDemo
.PHONY : AppMovingConcaveDemo

# fast build rule for target.
AppMovingConcaveDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/MovingConcaveDemo/CMakeFiles/AppMovingConcaveDemo.dir/build.make lib/bullet-2.79/Demos/MovingConcaveDemo/CMakeFiles/AppMovingConcaveDemo.dir/build
.PHONY : AppMovingConcaveDemo/fast

#=============================================================================
# Target rules for targets named AppVehicleDemo

# Build rule for target.
AppVehicleDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppVehicleDemo
.PHONY : AppVehicleDemo

# fast build rule for target.
AppVehicleDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/VehicleDemo/CMakeFiles/AppVehicleDemo.dir/build.make lib/bullet-2.79/Demos/VehicleDemo/CMakeFiles/AppVehicleDemo.dir/build
.PHONY : AppVehicleDemo/fast

#=============================================================================
# Target rules for targets named AppUserCollisionAlgorithm

# Build rule for target.
AppUserCollisionAlgorithm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppUserCollisionAlgorithm
.PHONY : AppUserCollisionAlgorithm

# fast build rule for target.
AppUserCollisionAlgorithm/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/UserCollisionAlgorithm/CMakeFiles/AppUserCollisionAlgorithm.dir/build.make lib/bullet-2.79/Demos/UserCollisionAlgorithm/CMakeFiles/AppUserCollisionAlgorithm.dir/build
.PHONY : AppUserCollisionAlgorithm/fast

#=============================================================================
# Target rules for targets named AppCharacterDemo

# Build rule for target.
AppCharacterDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppCharacterDemo
.PHONY : AppCharacterDemo

# fast build rule for target.
AppCharacterDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/CharacterDemo/CMakeFiles/AppCharacterDemo.dir/build.make lib/bullet-2.79/Demos/CharacterDemo/CMakeFiles/AppCharacterDemo.dir/build
.PHONY : AppCharacterDemo/fast

#=============================================================================
# Target rules for targets named AppSoftBodyDemo

# Build rule for target.
AppSoftBodyDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppSoftBodyDemo
.PHONY : AppSoftBodyDemo

# fast build rule for target.
AppSoftBodyDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/SoftDemo/CMakeFiles/AppSoftBodyDemo.dir/build.make lib/bullet-2.79/Demos/SoftDemo/CMakeFiles/AppSoftBodyDemo.dir/build
.PHONY : AppSoftBodyDemo/fast

#=============================================================================
# Target rules for targets named HfFluidDemo

# Build rule for target.
HfFluidDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HfFluidDemo
.PHONY : HfFluidDemo

# fast build rule for target.
HfFluidDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/HeightFieldFluidDemo/CMakeFiles/HfFluidDemo.dir/build.make lib/bullet-2.79/Demos/HeightFieldFluidDemo/CMakeFiles/HfFluidDemo.dir/build
.PHONY : HfFluidDemo/fast

#=============================================================================
# Target rules for targets named AppCollisionInterfaceDemo

# Build rule for target.
AppCollisionInterfaceDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppCollisionInterfaceDemo
.PHONY : AppCollisionInterfaceDemo

# fast build rule for target.
AppCollisionInterfaceDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/CollisionInterfaceDemo/CMakeFiles/AppCollisionInterfaceDemo.dir/build.make lib/bullet-2.79/Demos/CollisionInterfaceDemo/CMakeFiles/AppCollisionInterfaceDemo.dir/build
.PHONY : AppCollisionInterfaceDemo/fast

#=============================================================================
# Target rules for targets named AppConcaveConvexCastDemo

# Build rule for target.
AppConcaveConvexCastDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppConcaveConvexCastDemo
.PHONY : AppConcaveConvexCastDemo

# fast build rule for target.
AppConcaveConvexCastDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ConcaveConvexcastDemo/CMakeFiles/AppConcaveConvexCastDemo.dir/build.make lib/bullet-2.79/Demos/ConcaveConvexcastDemo/CMakeFiles/AppConcaveConvexCastDemo.dir/build
.PHONY : AppConcaveConvexCastDemo/fast

#=============================================================================
# Target rules for targets named AppSimplexDemo

# Build rule for target.
AppSimplexDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppSimplexDemo
.PHONY : AppSimplexDemo

# fast build rule for target.
AppSimplexDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/SimplexDemo/CMakeFiles/AppSimplexDemo.dir/build.make lib/bullet-2.79/Demos/SimplexDemo/CMakeFiles/AppSimplexDemo.dir/build
.PHONY : AppSimplexDemo/fast

#=============================================================================
# Target rules for targets named AppMotorDemo

# Build rule for target.
AppMotorDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppMotorDemo
.PHONY : AppMotorDemo

# fast build rule for target.
AppMotorDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/DynamicControlDemo/CMakeFiles/AppMotorDemo.dir/build.make lib/bullet-2.79/Demos/DynamicControlDemo/CMakeFiles/AppMotorDemo.dir/build
.PHONY : AppMotorDemo/fast

#=============================================================================
# Target rules for targets named AppConvexHullDistanceDemo

# Build rule for target.
AppConvexHullDistanceDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppConvexHullDistanceDemo
.PHONY : AppConvexHullDistanceDemo

# fast build rule for target.
AppConvexHullDistanceDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ConvexHullDistance/CMakeFiles/AppConvexHullDistanceDemo.dir/build.make lib/bullet-2.79/Demos/ConvexHullDistance/CMakeFiles/AppConvexHullDistanceDemo.dir/build
.PHONY : AppConvexHullDistanceDemo/fast

#=============================================================================
# Target rules for targets named AppDoublePrecisionDemo

# Build rule for target.
AppDoublePrecisionDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppDoublePrecisionDemo
.PHONY : AppDoublePrecisionDemo

# fast build rule for target.
AppDoublePrecisionDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/DoublePrecisionDemo/CMakeFiles/AppDoublePrecisionDemo.dir/build.make lib/bullet-2.79/Demos/DoublePrecisionDemo/CMakeFiles/AppDoublePrecisionDemo.dir/build
.PHONY : AppDoublePrecisionDemo/fast

#=============================================================================
# Target rules for targets named AppConcaveDemo

# Build rule for target.
AppConcaveDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppConcaveDemo
.PHONY : AppConcaveDemo

# fast build rule for target.
AppConcaveDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ConcaveDemo/CMakeFiles/AppConcaveDemo.dir/build.make lib/bullet-2.79/Demos/ConcaveDemo/CMakeFiles/AppConcaveDemo.dir/build
.PHONY : AppConcaveDemo/fast

#=============================================================================
# Target rules for targets named AppCollisionDemo

# Build rule for target.
AppCollisionDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppCollisionDemo
.PHONY : AppCollisionDemo

# fast build rule for target.
AppCollisionDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/CollisionDemo/CMakeFiles/AppCollisionDemo.dir/build.make lib/bullet-2.79/Demos/CollisionDemo/CMakeFiles/AppCollisionDemo.dir/build
.PHONY : AppCollisionDemo/fast

#=============================================================================
# Target rules for targets named AppContinuousConvexCollisionDemo

# Build rule for target.
AppContinuousConvexCollisionDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppContinuousConvexCollisionDemo
.PHONY : AppContinuousConvexCollisionDemo

# fast build rule for target.
AppContinuousConvexCollisionDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ContinuousConvexCollision/CMakeFiles/AppContinuousConvexCollisionDemo.dir/build.make lib/bullet-2.79/Demos/ContinuousConvexCollision/CMakeFiles/AppContinuousConvexCollisionDemo.dir/build
.PHONY : AppContinuousConvexCollisionDemo/fast

#=============================================================================
# Target rules for targets named AppConcaveRayCastDemo

# Build rule for target.
AppConcaveRayCastDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppConcaveRayCastDemo
.PHONY : AppConcaveRayCastDemo

# fast build rule for target.
AppConcaveRayCastDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ConcaveRaycastDemo/CMakeFiles/AppConcaveRayCastDemo.dir/build.make lib/bullet-2.79/Demos/ConcaveRaycastDemo/CMakeFiles/AppConcaveRayCastDemo.dir/build
.PHONY : AppConcaveRayCastDemo/fast

#=============================================================================
# Target rules for targets named AppLinearConvexCastDemo

# Build rule for target.
AppLinearConvexCastDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppLinearConvexCastDemo
.PHONY : AppLinearConvexCastDemo

# fast build rule for target.
AppLinearConvexCastDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/GjkConvexCastDemo/CMakeFiles/AppLinearConvexCastDemo.dir/build.make lib/bullet-2.79/Demos/GjkConvexCastDemo/CMakeFiles/AppLinearConvexCastDemo.dir/build
.PHONY : AppLinearConvexCastDemo/fast

#=============================================================================
# Target rules for targets named AppMultiMaterialDemo

# Build rule for target.
AppMultiMaterialDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppMultiMaterialDemo
.PHONY : AppMultiMaterialDemo

# fast build rule for target.
AppMultiMaterialDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/MultiMaterialDemo/CMakeFiles/AppMultiMaterialDemo.dir/build.make lib/bullet-2.79/Demos/MultiMaterialDemo/CMakeFiles/AppMultiMaterialDemo.dir/build
.PHONY : AppMultiMaterialDemo/fast

#=============================================================================
# Target rules for targets named AppSerializeDemo

# Build rule for target.
AppSerializeDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppSerializeDemo
.PHONY : AppSerializeDemo

# fast build rule for target.
AppSerializeDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/SerializeDemo/CMakeFiles/AppSerializeDemo.dir/build.make lib/bullet-2.79/Demos/SerializeDemo/CMakeFiles/AppSerializeDemo.dir/build
.PHONY : AppSerializeDemo/fast

#=============================================================================
# Target rules for targets named AppInternalEdgeDemo

# Build rule for target.
AppInternalEdgeDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppInternalEdgeDemo
.PHONY : AppInternalEdgeDemo

# fast build rule for target.
AppInternalEdgeDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/InternalEdgeDemo/CMakeFiles/AppInternalEdgeDemo.dir/build.make lib/bullet-2.79/Demos/InternalEdgeDemo/CMakeFiles/AppInternalEdgeDemo.dir/build
.PHONY : AppInternalEdgeDemo/fast

#=============================================================================
# Target rules for targets named AppMultiThreadedDemo

# Build rule for target.
AppMultiThreadedDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppMultiThreadedDemo
.PHONY : AppMultiThreadedDemo

# fast build rule for target.
AppMultiThreadedDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/MultiThreadedDemo/CMakeFiles/AppMultiThreadedDemo.dir/build.make lib/bullet-2.79/Demos/MultiThreadedDemo/CMakeFiles/AppMultiThreadedDemo.dir/build
.PHONY : AppMultiThreadedDemo/fast

#=============================================================================
# Target rules for targets named AppBenchmarks

# Build rule for target.
AppBenchmarks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppBenchmarks
.PHONY : AppBenchmarks

# fast build rule for target.
AppBenchmarks/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/Benchmarks/CMakeFiles/AppBenchmarks.dir/build.make lib/bullet-2.79/Demos/Benchmarks/CMakeFiles/AppBenchmarks.dir/build
.PHONY : AppBenchmarks/fast

#=============================================================================
# Target rules for targets named AppThreadingDemo

# Build rule for target.
AppThreadingDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppThreadingDemo
.PHONY : AppThreadingDemo

# fast build rule for target.
AppThreadingDemo/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/ThreadingDemo/CMakeFiles/AppThreadingDemo.dir/build.make lib/bullet-2.79/Demos/ThreadingDemo/CMakeFiles/AppThreadingDemo.dir/build
.PHONY : AppThreadingDemo/fast

#=============================================================================
# Target rules for targets named AppOpenCLClothDemo_Mini

# Build rule for target.
AppOpenCLClothDemo_Mini: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AppOpenCLClothDemo_Mini
.PHONY : AppOpenCLClothDemo_Mini

# fast build rule for target.
AppOpenCLClothDemo_Mini/fast:
	$(MAKE) -f lib/bullet-2.79/Demos/OpenCLClothDemo/MiniCL/CMakeFiles/AppOpenCLClothDemo_Mini.dir/build.make lib/bullet-2.79/Demos/OpenCLClothDemo/MiniCL/CMakeFiles/AppOpenCLClothDemo_Mini.dir/build
.PHONY : AppOpenCLClothDemo_Mini/fast

#=============================================================================
# Target rules for targets named ConvexDecomposition

# Build rule for target.
ConvexDecomposition: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ConvexDecomposition
.PHONY : ConvexDecomposition

# fast build rule for target.
ConvexDecomposition/fast:
	$(MAKE) -f lib/bullet-2.79/Extras/ConvexDecomposition/CMakeFiles/ConvexDecomposition.dir/build.make lib/bullet-2.79/Extras/ConvexDecomposition/CMakeFiles/ConvexDecomposition.dir/build
.PHONY : ConvexDecomposition/fast

#=============================================================================
# Target rules for targets named HACD

# Build rule for target.
HACD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HACD
.PHONY : HACD

# fast build rule for target.
HACD/fast:
	$(MAKE) -f lib/bullet-2.79/Extras/HACD/CMakeFiles/HACD.dir/build.make lib/bullet-2.79/Extras/HACD/CMakeFiles/HACD.dir/build
.PHONY : HACD/fast

#=============================================================================
# Target rules for targets named GIMPACTUtils

# Build rule for target.
GIMPACTUtils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GIMPACTUtils
.PHONY : GIMPACTUtils

# fast build rule for target.
GIMPACTUtils/fast:
	$(MAKE) -f lib/bullet-2.79/Extras/GIMPACTUtils/CMakeFiles/GIMPACTUtils.dir/build.make lib/bullet-2.79/Extras/GIMPACTUtils/CMakeFiles/GIMPACTUtils.dir/build
.PHONY : GIMPACTUtils/fast

#=============================================================================
# Target rules for targets named GLUI

# Build rule for target.
GLUI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GLUI
.PHONY : GLUI

# fast build rule for target.
GLUI/fast:
	$(MAKE) -f lib/bullet-2.79/Extras/glui/CMakeFiles/GLUI.dir/build.make lib/bullet-2.79/Extras/glui/CMakeFiles/GLUI.dir/build
.PHONY : GLUI/fast

#=============================================================================
# Target rules for targets named BulletFileLoader

# Build rule for target.
BulletFileLoader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletFileLoader
.PHONY : BulletFileLoader

# fast build rule for target.
BulletFileLoader/fast:
	$(MAKE) -f lib/bullet-2.79/Extras/Serialize/BulletFileLoader/CMakeFiles/BulletFileLoader.dir/build.make lib/bullet-2.79/Extras/Serialize/BulletFileLoader/CMakeFiles/BulletFileLoader.dir/build
.PHONY : BulletFileLoader/fast

#=============================================================================
# Target rules for targets named BulletWorldImporter

# Build rule for target.
BulletWorldImporter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletWorldImporter
.PHONY : BulletWorldImporter

# fast build rule for target.
BulletWorldImporter/fast:
	$(MAKE) -f lib/bullet-2.79/Extras/Serialize/BulletWorldImporter/CMakeFiles/BulletWorldImporter.dir/build.make lib/bullet-2.79/Extras/Serialize/BulletWorldImporter/CMakeFiles/BulletWorldImporter.dir/build
.PHONY : BulletWorldImporter/fast

#=============================================================================
# Target rules for targets named MiniCL

# Build rule for target.
MiniCL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MiniCL
.PHONY : MiniCL

# fast build rule for target.
MiniCL/fast:
	$(MAKE) -f lib/bullet-2.79/src/MiniCL/CMakeFiles/MiniCL.dir/build.make lib/bullet-2.79/src/MiniCL/CMakeFiles/MiniCL.dir/build
.PHONY : MiniCL/fast

#=============================================================================
# Target rules for targets named BulletMultiThreaded

# Build rule for target.
BulletMultiThreaded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletMultiThreaded
.PHONY : BulletMultiThreaded

# fast build rule for target.
BulletMultiThreaded/fast:
	$(MAKE) -f lib/bullet-2.79/src/BulletMultiThreaded/CMakeFiles/BulletMultiThreaded.dir/build.make lib/bullet-2.79/src/BulletMultiThreaded/CMakeFiles/BulletMultiThreaded.dir/build
.PHONY : BulletMultiThreaded/fast

#=============================================================================
# Target rules for targets named BulletSoftBody

# Build rule for target.
BulletSoftBody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletSoftBody
.PHONY : BulletSoftBody

# fast build rule for target.
BulletSoftBody/fast:
	$(MAKE) -f lib/bullet-2.79/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build.make lib/bullet-2.79/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build
.PHONY : BulletSoftBody/fast

#=============================================================================
# Target rules for targets named BulletCollision

# Build rule for target.
BulletCollision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletCollision
.PHONY : BulletCollision

# fast build rule for target.
BulletCollision/fast:
	$(MAKE) -f lib/bullet-2.79/src/BulletCollision/CMakeFiles/BulletCollision.dir/build.make lib/bullet-2.79/src/BulletCollision/CMakeFiles/BulletCollision.dir/build
.PHONY : BulletCollision/fast

#=============================================================================
# Target rules for targets named BulletDynamics

# Build rule for target.
BulletDynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletDynamics
.PHONY : BulletDynamics

# fast build rule for target.
BulletDynamics/fast:
	$(MAKE) -f lib/bullet-2.79/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build.make lib/bullet-2.79/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build
.PHONY : BulletDynamics/fast

#=============================================================================
# Target rules for targets named LinearMath

# Build rule for target.
LinearMath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinearMath
.PHONY : LinearMath

# fast build rule for target.
LinearMath/fast:
	$(MAKE) -f lib/bullet-2.79/src/LinearMath/CMakeFiles/LinearMath.dir/build.make lib/bullet-2.79/src/LinearMath/CMakeFiles/LinearMath.dir/build
.PHONY : LinearMath/fast

#=============================================================================
# Target rules for targets named BulletSoftBodySolvers_CPU

# Build rule for target.
BulletSoftBodySolvers_CPU: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletSoftBodySolvers_CPU
.PHONY : BulletSoftBodySolvers_CPU

# fast build rule for target.
BulletSoftBodySolvers_CPU/fast:
	$(MAKE) -f lib/bullet-2.79/src/BulletMultiThreaded/GpuSoftBodySolvers/CPU/CMakeFiles/BulletSoftBodySolvers_CPU.dir/build.make lib/bullet-2.79/src/BulletMultiThreaded/GpuSoftBodySolvers/CPU/CMakeFiles/BulletSoftBodySolvers_CPU.dir/build
.PHONY : BulletSoftBodySolvers_CPU/fast

#=============================================================================
# Target rules for targets named BulletSoftBodySolvers_OpenCL_Mini

# Build rule for target.
BulletSoftBodySolvers_OpenCL_Mini: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletSoftBodySolvers_OpenCL_Mini
.PHONY : BulletSoftBodySolvers_OpenCL_Mini

# fast build rule for target.
BulletSoftBodySolvers_OpenCL_Mini/fast:
	$(MAKE) -f lib/bullet-2.79/src/BulletMultiThreaded/GpuSoftBodySolvers/OpenCL/MiniCL/CMakeFiles/BulletSoftBodySolvers_OpenCL_Mini.dir/build.make lib/bullet-2.79/src/BulletMultiThreaded/GpuSoftBodySolvers/OpenCL/MiniCL/CMakeFiles/BulletSoftBodySolvers_OpenCL_Mini.dir/build
.PHONY : BulletSoftBodySolvers_OpenCL_Mini/fast

#=============================================================================
# Target rules for targets named osgWorks

# Build rule for target.
osgWorks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgWorks
.PHONY : osgWorks

# fast build rule for target.
osgWorks/fast:
	$(MAKE) -f lib/osgWorks-2.0/CMakeFiles/osgWorks.dir/build.make lib/osgWorks-2.0/CMakeFiles/osgWorks.dir/build
.PHONY : osgWorks/fast

#=============================================================================
# Target rules for targets named osgBullet

# Build rule for target.
osgBullet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgBullet
.PHONY : osgBullet

# fast build rule for target.
osgBullet/fast:
	$(MAKE) -f lib/osgBullet-2.0/CMakeFiles/osgBullet.dir/build.make lib/osgBullet-2.0/CMakeFiles/osgBullet.dir/build
.PHONY : osgBullet/fast

#=============================================================================
# Target rules for targets named LaundryBot

# Build rule for target.
LaundryBot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaundryBot
.PHONY : LaundryBot

# fast build rule for target.
LaundryBot/fast:
	$(MAKE) -f src/CMakeFiles/LaundryBot.dir/build.make src/CMakeFiles/LaundryBot.dir/build
.PHONY : LaundryBot/fast

#=============================================================================
# Target rules for targets named simplescene_test

# Build rule for target.
simplescene_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplescene_test
.PHONY : simplescene_test

# fast build rule for target.
simplescene_test/fast:
	$(MAKE) -f src/CMakeFiles/simplescene_test.dir/build.make src/CMakeFiles/simplescene_test.dir/build
.PHONY : simplescene_test/fast

#=============================================================================
# Target rules for targets named simulation

# Build rule for target.
simulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulation
.PHONY : simulation

# fast build rule for target.
simulation/fast:
	$(MAKE) -f src/CMakeFiles/simulation.dir/build.make src/CMakeFiles/simulation.dir/build
.PHONY : simulation/fast

#=============================================================================
# Target rules for targets named softbody_test

# Build rule for target.
softbody_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 softbody_test
.PHONY : softbody_test

# fast build rule for target.
softbody_test/fast:
	$(MAKE) -f src/CMakeFiles/softbody_test.dir/build.make src/CMakeFiles/softbody_test.dir/build
.PHONY : softbody_test/fast

#=============================================================================
# Target rules for targets named test_rope

# Build rule for target.
test_rope: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rope
.PHONY : test_rope

# fast build rule for target.
test_rope/fast:
	$(MAKE) -f src/CMakeFiles/test_rope.dir/build.make src/CMakeFiles/test_rope.dir/build
.PHONY : test_rope/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... haptics"
	@echo "... AppHelloWorld"
	@echo "... OpenGLSupport"
	@echo "... AppAllBulletDemos"
	@echo "... AppConvexDecompositionDemo"
	@echo "... AppCcdPhysicsDemo"
	@echo "... AppConstraintDemo"
	@echo "... AppSliderConstraintDemo"
	@echo "... AppGenericJointDemo"
	@echo "... AppRaytracer"
	@echo "... AppRagdollDemo"
	@echo "... AppForkLiftDemo"
	@echo "... AppBasicDemo"
	@echo "... AppFractureDemo"
	@echo "... AppBox2dDemo"
	@echo "... AppBspPhysicsDemo"
	@echo "... AppMovingConcaveDemo"
	@echo "... AppVehicleDemo"
	@echo "... AppUserCollisionAlgorithm"
	@echo "... AppCharacterDemo"
	@echo "... AppSoftBodyDemo"
	@echo "... HfFluidDemo"
	@echo "... AppCollisionInterfaceDemo"
	@echo "... AppConcaveConvexCastDemo"
	@echo "... AppSimplexDemo"
	@echo "... AppMotorDemo"
	@echo "... AppConvexHullDistanceDemo"
	@echo "... AppDoublePrecisionDemo"
	@echo "... AppConcaveDemo"
	@echo "... AppCollisionDemo"
	@echo "... AppContinuousConvexCollisionDemo"
	@echo "... AppConcaveRayCastDemo"
	@echo "... AppLinearConvexCastDemo"
	@echo "... AppMultiMaterialDemo"
	@echo "... AppSerializeDemo"
	@echo "... AppInternalEdgeDemo"
	@echo "... AppMultiThreadedDemo"
	@echo "... AppBenchmarks"
	@echo "... AppThreadingDemo"
	@echo "... AppOpenCLClothDemo_Mini"
	@echo "... ConvexDecomposition"
	@echo "... HACD"
	@echo "... GIMPACTUtils"
	@echo "... GLUI"
	@echo "... BulletFileLoader"
	@echo "... BulletWorldImporter"
	@echo "... MiniCL"
	@echo "... BulletMultiThreaded"
	@echo "... BulletSoftBody"
	@echo "... BulletCollision"
	@echo "... BulletDynamics"
	@echo "... LinearMath"
	@echo "... BulletSoftBodySolvers_CPU"
	@echo "... BulletSoftBodySolvers_OpenCL_Mini"
	@echo "... osgWorks"
	@echo "... osgBullet"
	@echo "... LaundryBot"
	@echo "... simplescene_test"
	@echo "... simulation"
	@echo "... softbody_test"
	@echo "... test_rope"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

